apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/jduimovich0/devfile-sample-go-basic@sha256:5fb9ec9c5ab1ac794f11d099ae57621801699347276cb49bf97e6da90c377346
        name: my-go
        resources: {}
status: {}
